#!/usr/bin/env bash

check_factor() {
    local num1=$1
    local num2=$2
    local result

    if [ $num2 -gt $num1 ]; then
        local temp=$num1
        num1=$num2
        num2=$temp
    fi

    echo "$num1 * $num2"
}

if [ $# -ne 1 ]; then
    echo 'Usage: factors <file>'
    exit 1
fi

while read -r num; do
    result=$(factor "$num" | tr -d '[:alpha:]')
    factors=($result)
    check_factor "${factors[@]}"
done < "$1"

